### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [TommasoVandermeer/Social-Navigation-PyEnvs#1]
Under what license is this project released under ? It seems like a very interesting environment. I would like to study it to learn how to make similar environments for reinforcement learning. Thanks.

**Comment by TommasoVandermeer** [comment]
Sorry for the delay in my response, the repository was not ready to be used yet. Currently the project is released under Apache-2.0 license, you can find the terms and conditions in the LICENSE file. 

Note that, since you posted this issue, the repository has undergone several changes. 

I hope this will help you.
